default: &max_conn 10000
entity:
  persistence:
    interval: 60s
  cache:
    size: *max_conn
    stat: true

io-netty:
#  host: 127.0.0.1
  port: 5555
#  poolSize: 8
#  options:
#  childOptions:
  frameLengthMax: 1k
  connectionsMax: *max_conn
  msgNumPerSecond: 20
  compressThreshold: 1k
  readTimeout: 60s
  heartbeatInterval: 60s
  anonymousChannelCloseDelay: 30s
  codec: string

resource:
    reader: json
    path: resource